# Generated by Django 5.2.5 on 2025-08-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('ana_yemek', 'Ana Yemek'), ('icecek', 'İçecek'), ('tatli', 'Tatlı'), ('aperatif', 'Aperatif')], default='ana_yemek', max_length=20),
        ),
    ]
