# Generated by Django 5.2.5 on 2025-08-14 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('order_placed', 'Order Placed'), ('order_status_changed', 'Order Status Changed'), ('stock_updated', 'Stock Updated'), ('user_created', 'User Created'), ('user_modified', 'User Modified'), ('price_changed', 'Price Changed'), ('item_cancelled', 'Item Cancelled')], max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action'], name='users_audit_user_id_c6aa5b_idx'), models.Index(fields=['action', 'timestamp'], name='users_audit_action_962101_idx'), models.Index(fields=['resource_type', 'resource_id'], name='users_audit_resourc_156f16_idx'), models.Index(fields=['timestamp'], name='users_audit_timesta_45d1d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_new', 'New Order'), ('order_status', 'Order Status Change'), ('stock_low', 'Low Stock'), ('user_activity', 'User Activity'), ('system_alert', 'System Alert')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read'], name='users_notif_recipie_29f6f4_idx'), models.Index(fields=['notification_type', 'created_at'], name='users_notif_notific_5f4a5e_idx'), models.Index(fields=['priority', 'created_at'], name='users_notif_priorit_a95b3b_idx')],
            },
        ),
    ]
