# Generated by Django 5.2.5 on 2025-08-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_order_total_orderitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_restocked',
            field=models.BooleanField(default=False),
        ),
    ]
