# Generated by Django 5.2.5 on 2025-08-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_is_restocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_restocked',
        ),
    ]
