# Generated by Django 5.2.5 on 2025-08-14 08:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='menu_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['menu_item'], name='stock_stock_menu_it_494113_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['quantity'], name='stock_stock_quantit_ffb26c_idx'),
        ),
    ]
